/*
 * Sequence Optimization
 *
 * With the Sequence Optimization service you can find the best route for your transports.
 *
 * The version of the OpenAPI document: 1.8
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.sequenceoptimization.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.sequenceoptimization.Model
{
    /// <summary>
    /// Wrapper around a unique ID for an optimized route.
    /// </summary>
    [DataContract(Name = "OptimizedRouteIdentifier")]
    public partial class OptimizedRouteIdentifier : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OptimizedRouteIdentifier" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OptimizedRouteIdentifier() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OptimizedRouteIdentifier" /> class.
        /// </summary>
        /// <param name="id">A unique ID for an optimized route. This ID can be used to delete or get the result of a sequence optimization. (required).</param>
        public OptimizedRouteIdentifier(Guid id = default(Guid))
        {
            this.Id = id;
        }

        /// <summary>
        /// A unique ID for an optimized route. This ID can be used to delete or get the result of a sequence optimization.
        /// </summary>
        /// <value>A unique ID for an optimized route. This ID can be used to delete or get the result of a sequence optimization.</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OptimizedRouteIdentifier {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
