/*
 * Sequence Optimization
 *
 * With the Sequence Optimization service you can find the best route for your transports.
 *
 * The version of the OpenAPI document: 1.8
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.sequenceoptimization.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.sequenceoptimization.Model
{
    /// <summary>
    /// The vehicle used to transport goods.
    /// </summary>
    [DataContract(Name = "Vehicle")]
    public partial class Vehicle : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Vehicle" /> class.
        /// </summary>
        /// <param name="capacities">The list of capacities for the different quantity dimensions of goods that can be transported. The maximum length of this list is 100. That is, up to 100 different quantity dimensions (e.g. number of pallets, weight, volume, etc.) can be distinguished. Transports can only be executed by a vehicle with a higher (or an equal) maximum capacity in every quantity dimension. The length of this list has to be the same for all transports and the vehicle. If and only if this list of capacities is empty for the given vehicle, the quantities of each transport must be empty..</param>
        /// <param name="profile">The profile defines attributes of the vehicle relevant to determine travel times and distances between any two locations.   See [here](./concepts/profiles-and-countries) for a complete list of allowed values. If the majority of locations are in the Americas, _USA_1_PICKUP_ is used as the default. Otherwise, _EUR_VAN_ is used as the default.  If most locations are located in the Americas but a non-American vehicle profile is specified or vice-versa, a warning is returned. Always use a vehicle profile which matches the region of the locations to obtain best results..</param>
        /// <param name="startLocationId">ID of the vehicle&#39;s start location. If vehicle&#39;s start location does not coincide with the location of the first pickup, only the coordinates of vehicle&#39;s start location are considered and all other attributes such as opening intervals, service time or type are ignored. If no start location is specified, it is assumed that the vehicle is available at the first stop..</param>
        /// <param name="endLocationId">ID of the vehicle&#39;s end location. If vehicle&#39;s end location does not coincide with the location of the last delivery, only the coordinates of vehicle&#39;s end location are considered and all other attributes such as opening intervals, service time or type are ignored. If no end location is specified, it is assumed that the vehicle remains at the last stop..</param>
        /// <param name="routeStartInterval">Interval in which the vehicle has to start its route. Start and end of the interval may be the same. Leaving this parameter empty means that the route start is unrestricted..</param>
        /// <param name="maximumDistance">Restricts the maximum allowed total driving distance [m] for the route of the vehicle..</param>
        public Vehicle(List<int?> capacities = default(List<int?>), string profile = default(string), string startLocationId = default(string), string endLocationId = default(string), TimeInterval routeStartInterval = default(TimeInterval), int? maximumDistance = default(int?))
        {
            this.Capacities = capacities;
            this.Profile = profile;
            this.StartLocationId = startLocationId;
            this.EndLocationId = endLocationId;
            this.RouteStartInterval = routeStartInterval;
            this.MaximumDistance = maximumDistance;
        }

        /// <summary>
        /// The list of capacities for the different quantity dimensions of goods that can be transported. The maximum length of this list is 100. That is, up to 100 different quantity dimensions (e.g. number of pallets, weight, volume, etc.) can be distinguished. Transports can only be executed by a vehicle with a higher (or an equal) maximum capacity in every quantity dimension. The length of this list has to be the same for all transports and the vehicle. If and only if this list of capacities is empty for the given vehicle, the quantities of each transport must be empty.
        /// </summary>
        /// <value>The list of capacities for the different quantity dimensions of goods that can be transported. The maximum length of this list is 100. That is, up to 100 different quantity dimensions (e.g. number of pallets, weight, volume, etc.) can be distinguished. Transports can only be executed by a vehicle with a higher (or an equal) maximum capacity in every quantity dimension. The length of this list has to be the same for all transports and the vehicle. If and only if this list of capacities is empty for the given vehicle, the quantities of each transport must be empty.</value>
        [DataMember(Name = "capacities", EmitDefaultValue = false)]
        public List<int?> Capacities { get; set; }

        /// <summary>
        /// The profile defines attributes of the vehicle relevant to determine travel times and distances between any two locations.   See [here](./concepts/profiles-and-countries) for a complete list of allowed values. If the majority of locations are in the Americas, _USA_1_PICKUP_ is used as the default. Otherwise, _EUR_VAN_ is used as the default.  If most locations are located in the Americas but a non-American vehicle profile is specified or vice-versa, a warning is returned. Always use a vehicle profile which matches the region of the locations to obtain best results.
        /// </summary>
        /// <value>The profile defines attributes of the vehicle relevant to determine travel times and distances between any two locations.   See [here](./concepts/profiles-and-countries) for a complete list of allowed values. If the majority of locations are in the Americas, _USA_1_PICKUP_ is used as the default. Otherwise, _EUR_VAN_ is used as the default.  If most locations are located in the Americas but a non-American vehicle profile is specified or vice-versa, a warning is returned. Always use a vehicle profile which matches the region of the locations to obtain best results.</value>
        [DataMember(Name = "profile", EmitDefaultValue = false)]
        public string Profile { get; set; }

        /// <summary>
        /// ID of the vehicle&#39;s start location. If vehicle&#39;s start location does not coincide with the location of the first pickup, only the coordinates of vehicle&#39;s start location are considered and all other attributes such as opening intervals, service time or type are ignored. If no start location is specified, it is assumed that the vehicle is available at the first stop.
        /// </summary>
        /// <value>ID of the vehicle&#39;s start location. If vehicle&#39;s start location does not coincide with the location of the first pickup, only the coordinates of vehicle&#39;s start location are considered and all other attributes such as opening intervals, service time or type are ignored. If no start location is specified, it is assumed that the vehicle is available at the first stop.</value>
        [DataMember(Name = "startLocationId", EmitDefaultValue = false)]
        public string StartLocationId { get; set; }

        /// <summary>
        /// ID of the vehicle&#39;s end location. If vehicle&#39;s end location does not coincide with the location of the last delivery, only the coordinates of vehicle&#39;s end location are considered and all other attributes such as opening intervals, service time or type are ignored. If no end location is specified, it is assumed that the vehicle remains at the last stop.
        /// </summary>
        /// <value>ID of the vehicle&#39;s end location. If vehicle&#39;s end location does not coincide with the location of the last delivery, only the coordinates of vehicle&#39;s end location are considered and all other attributes such as opening intervals, service time or type are ignored. If no end location is specified, it is assumed that the vehicle remains at the last stop.</value>
        [DataMember(Name = "endLocationId", EmitDefaultValue = false)]
        public string EndLocationId { get; set; }

        /// <summary>
        /// Interval in which the vehicle has to start its route. Start and end of the interval may be the same. Leaving this parameter empty means that the route start is unrestricted.
        /// </summary>
        /// <value>Interval in which the vehicle has to start its route. Start and end of the interval may be the same. Leaving this parameter empty means that the route start is unrestricted.</value>
        [DataMember(Name = "routeStartInterval", EmitDefaultValue = false)]
        public TimeInterval RouteStartInterval { get; set; }

        /// <summary>
        /// Restricts the maximum allowed total driving distance [m] for the route of the vehicle.
        /// </summary>
        /// <value>Restricts the maximum allowed total driving distance [m] for the route of the vehicle.</value>
        [DataMember(Name = "maximumDistance", EmitDefaultValue = true)]
        public int? MaximumDistance { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Vehicle {\n");
            sb.Append("  Capacities: ").Append(Capacities).Append("\n");
            sb.Append("  Profile: ").Append(Profile).Append("\n");
            sb.Append("  StartLocationId: ").Append(StartLocationId).Append("\n");
            sb.Append("  EndLocationId: ").Append(EndLocationId).Append("\n");
            sb.Append("  RouteStartInterval: ").Append(RouteStartInterval).Append("\n");
            sb.Append("  MaximumDistance: ").Append(MaximumDistance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (this.StartLocationId != null) {
                // StartLocationId (string) pattern
                Regex regexStartLocationId = new Regex(@".*[^ ].*", RegexOptions.CultureInvariant);
                if (!regexStartLocationId.Match(this.StartLocationId).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for StartLocationId, must match a pattern of " + regexStartLocationId, new [] { "StartLocationId" });
                }
            }

            if (this.EndLocationId != null) {
                // EndLocationId (string) pattern
                Regex regexEndLocationId = new Regex(@".*[^ ].*", RegexOptions.CultureInvariant);
                if (!regexEndLocationId.Match(this.EndLocationId).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EndLocationId, must match a pattern of " + regexEndLocationId, new [] { "EndLocationId" });
                }
            }

            yield break;
        }
    }

}
