/*
 * Sequence Optimization
 * With the Sequence Optimization service you can find the best route for your transports.
 *
 * The version of the OpenAPI document: 1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.sequenceoptimization.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import io.swagger.annotations.ApiModel;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * If specified, this stop has to be the very first/last customer stop in the route whenever there is a stop at this location. There can only be one stop at a customer location with a position in route of type FIRST_CUSTOMER_STOP/LAST_CUSTOMER_STOP.   If specified, routeSectionNumber must not be set for the same location.   * &#x60;FIRST_CUSTOMER_STOP&#x60; - A stop at a customer location with this position type has to be the very first customer stop in the route.  * &#x60;LAST_CUSTOMER_STOP&#x60; - A stop at a customer location with this position type has to be the very last customer stop in the route.  See [here](./Concepts/Route%20sections%20and%20Position%20in%20route.htm) for more information.
 */
public enum PositionInRoute {
  
  FIRST_CUSTOMER_STOP("FIRST_CUSTOMER_STOP"),
  
  LAST_CUSTOMER_STOP("LAST_CUSTOMER_STOP");

  private String value;

  PositionInRoute(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static PositionInRoute fromValue(String value) {
    for (PositionInRoute b : PositionInRoute.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return null;
  }
}

