/*
 * Sequence Optimization
 * With the Sequence Optimization service you can find the best route for your transports.
 *
 * The version of the OpenAPI document: 1.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.sequenceoptimization.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ptvgroup.developer.client.sequenceoptimization.model.StopsSequence;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.ptvgroup.developer.client.sequenceoptimization.ApiClient;
/**
 * Contains restrictions that are to be considered during sequence optimization.
 */
@JsonPropertyOrder({
  Restrictions.JSON_PROPERTY_SEQUENCE_OF_STOPS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-27T08:41:48.082993405Z[Etc/UTC]", comments = "Generator version: 7.9.0")
public class Restrictions {
  public static final String JSON_PROPERTY_SEQUENCE_OF_STOPS = "sequenceOfStops";
  private StopsSequence sequenceOfStops = StopsSequence.ANY;

  public Restrictions() { 
  }

  public Restrictions sequenceOfStops(StopsSequence sequenceOfStops) {
    this.sequenceOfStops = sequenceOfStops;
    return this;
  }

  /**
   * Get sequenceOfStops
   * @return sequenceOfStops
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEQUENCE_OF_STOPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StopsSequence getSequenceOfStops() {
    return sequenceOfStops;
  }


  @JsonProperty(JSON_PROPERTY_SEQUENCE_OF_STOPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSequenceOfStops(StopsSequence sequenceOfStops) {
    this.sequenceOfStops = sequenceOfStops;
  }


  /**
   * Return true if this Restrictions object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Restrictions restrictions = (Restrictions) o;
    return Objects.equals(this.sequenceOfStops, restrictions.sequenceOfStops);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sequenceOfStops);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Restrictions {\n");
    sb.append("    sequenceOfStops: ").append(toIndentedString(sequenceOfStops)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `sequenceOfStops` to the URL query string
    if (getSequenceOfStops() != null) {
      joiner.add(String.format("%ssequenceOfStops%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getSequenceOfStops()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

