/* tslint:disable */
/* eslint-disable */
/**
 * Sequence Optimization
 * With the Sequence Optimization service you can find the best route for your transports.
 *
 * The version of the OpenAPI document: 1.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Attributes for a location of type DEPOT.
 * @export
 * @interface DepotLocationAttributes
 */
export interface DepotLocationAttributes {
    /**
     * The service time [s] that is required each time this location is visited in order to pick up goods. The location-dependent service time represents, for example, the time to enter the premises or to register at a depot. Besides a location-dependent service time, the user may specify an additional transport-dependent service time at the transports.
     * @type {number}
     * @memberof DepotLocationAttributes
     */
    serviceTimePerPickupStop?: number;
    /**
     * The service time [s] that is required each time this location is visited in order to deliver goods. The location-dependent service time represents, for example, the time to enter the premises or to register at a depot. Besides a location-dependent service time, the user may specify an additional transport-dependent service time at the transports.
     * @type {number}
     * @memberof DepotLocationAttributes
     */
    serviceTimePerDeliveryStop?: number;
}

/**
 * Check if a given object implements the DepotLocationAttributes interface.
 */
export function instanceOfDepotLocationAttributes(value: object): value is DepotLocationAttributes {
    return true;
}

export function DepotLocationAttributesFromJSON(json: any): DepotLocationAttributes {
    return DepotLocationAttributesFromJSONTyped(json, false);
}

export function DepotLocationAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepotLocationAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceTimePerPickupStop': json['serviceTimePerPickupStop'] == null ? undefined : json['serviceTimePerPickupStop'],
        'serviceTimePerDeliveryStop': json['serviceTimePerDeliveryStop'] == null ? undefined : json['serviceTimePerDeliveryStop'],
    };
}

  export function DepotLocationAttributesToJSON(json: any): DepotLocationAttributes {
      return DepotLocationAttributesToJSONTyped(json, false);
  }

  export function DepotLocationAttributesToJSONTyped(value?: DepotLocationAttributes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serviceTimePerPickupStop': value['serviceTimePerPickupStop'],
        'serviceTimePerDeliveryStop': value['serviceTimePerDeliveryStop'],
    };
}

