/* tslint:disable */
/* eslint-disable */
/**
 * Sequence Optimization
 * With the Sequence Optimization service you can find the best route for your transports.
 *
 * The version of the OpenAPI document: 1.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status of the corresponding start optimization operation or call.
 * @export
 */
export const OperationStatus = {
    RUNNING: 'RUNNING',
    SUCCEEDED: 'SUCCEEDED',
    FAILED: 'FAILED'
} as const;
export type OperationStatus = typeof OperationStatus[keyof typeof OperationStatus];


export function instanceOfOperationStatus(value: any): boolean {
    for (const key in OperationStatus) {
        if (Object.prototype.hasOwnProperty.call(OperationStatus, key)) {
            if (OperationStatus[key as keyof typeof OperationStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OperationStatusFromJSON(json: any): OperationStatus {
    return OperationStatusFromJSONTyped(json, false);
}

export function OperationStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationStatus {
    return json as OperationStatus;
}

export function OperationStatusToJSON(value?: OperationStatus | null): any {
    return value as any;
}

export function OperationStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): OperationStatus {
    return value as OperationStatus;
}

