/* tslint:disable */
/* eslint-disable */
/**
 * Sequence Optimization
 * With the Sequence Optimization service you can find the best route for your transports.
 *
 * The version of the OpenAPI document: 1.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Warning } from './Warning';
import {
    WarningFromJSON,
    WarningFromJSONTyped,
    WarningToJSON,
    WarningToJSONTyped,
} from './Warning';
import type { OperationStatus } from './OperationStatus';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus';
import type { OptimizedRoute } from './OptimizedRoute';
import {
    OptimizedRouteFromJSON,
    OptimizedRouteFromJSONTyped,
    OptimizedRouteToJSON,
    OptimizedRouteToJSONTyped,
} from './OptimizedRoute';
import type { ErrorResponse } from './ErrorResponse';
import {
    ErrorResponseFromJSON,
    ErrorResponseFromJSONTyped,
    ErrorResponseToJSON,
    ErrorResponseToJSONTyped,
} from './ErrorResponse';

/**
 * Contains the results of an optimization. If the 'status' is 'RUNNING', the calculation is still running and no further properties are set. If the 'status' is 'SUCCEEDED', the optimization result is present as property 'optimizedRoute'. If the 'status' is 'FAILED', the failure result is present as property 'error'.
 * @export
 * @interface OptimizedRouteResponse
 */
export interface OptimizedRouteResponse {
    /**
     * 
     * @type {OperationStatus}
     * @memberof OptimizedRouteResponse
     */
    status: OperationStatus;
    /**
     * 
     * @type {OptimizedRoute}
     * @memberof OptimizedRouteResponse
     */
    optimizedRoute?: OptimizedRoute;
    /**
     * A human readable message that describes the error. Set and used only when operation status is FAILED.
     * @type {ErrorResponse}
     * @memberof OptimizedRouteResponse
     */
    error?: ErrorResponse;
    /**
     * A list of warnings concerning the validity of the result.
     * @type {Array<Warning>}
     * @memberof OptimizedRouteResponse
     */
    warnings?: Array<Warning>;
}



/**
 * Check if a given object implements the OptimizedRouteResponse interface.
 */
export function instanceOfOptimizedRouteResponse(value: object): value is OptimizedRouteResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function OptimizedRouteResponseFromJSON(json: any): OptimizedRouteResponse {
    return OptimizedRouteResponseFromJSONTyped(json, false);
}

export function OptimizedRouteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptimizedRouteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'optimizedRoute': json['optimizedRoute'] == null ? undefined : OptimizedRouteFromJSON(json['optimizedRoute']),
        'error': json['error'] == null ? undefined : ErrorResponseFromJSON(json['error']),
        'warnings': json['warnings'] == null ? undefined : ((json['warnings'] as Array<any>).map(WarningFromJSON)),
    };
}

  export function OptimizedRouteResponseToJSON(json: any): OptimizedRouteResponse {
      return OptimizedRouteResponseToJSONTyped(json, false);
  }

  export function OptimizedRouteResponseToJSONTyped(value?: OptimizedRouteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'optimizedRoute': OptimizedRouteToJSON(value['optimizedRoute']),
        'error': ErrorResponseToJSON(value['error']),
        'warnings': value['warnings'] == null ? undefined : ((value['warnings'] as Array<any>).map(WarningToJSON)),
    };
}

