/* tslint:disable */
/* eslint-disable */
/**
 * Sequence Optimization
 * With the Sequence Optimization service you can find the best route for your transports.
 *
 * The version of the OpenAPI document: 1.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Indicates if and how the sequence of stops that is already part of the input route, should be retained. Will be ignored, if there are no stops in input route.
 *  * `ANY` - Sequence of stops already in input route can be modified arbitrarily in order to obtain an optimal route.
 *  * `RELATIVE` - Relative sequence of stops as given in input route should be retained.
 * @export
 */
export const StopsSequence = {
    ANY: 'ANY',
    RELATIVE: 'RELATIVE'
} as const;
export type StopsSequence = typeof StopsSequence[keyof typeof StopsSequence];


export function instanceOfStopsSequence(value: any): boolean {
    for (const key in StopsSequence) {
        if (Object.prototype.hasOwnProperty.call(StopsSequence, key)) {
            if (StopsSequence[key as keyof typeof StopsSequence] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StopsSequenceFromJSON(json: any): StopsSequence {
    return StopsSequenceFromJSONTyped(json, false);
}

export function StopsSequenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): StopsSequence {
    return json as StopsSequence;
}

export function StopsSequenceToJSON(value?: StopsSequence | null): any {
    return value as any;
}

export function StopsSequenceToJSONTyped(value: any, ignoreDiscriminator: boolean): StopsSequence {
    return value as StopsSequence;
}

