/* tslint:disable */
/* eslint-disable */
/**
 * Sequence Optimization
 * With the Sequence Optimization service you can find the best route for your transports.
 *
 * The version of the OpenAPI document: 1.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A way report contains a summary of the values of the events on the way from the previous stop to the current stop, including the driving time. The very first stop of a route has a way report with empty values.
 * @export
 * @interface WayReport
 */
export interface WayReport {
    /**
     * The driving distance from the previous stop to this stop [m].
     * @type {number}
     * @memberof WayReport
     */
    distance: number;
    /**
     * The driving time from the previous stop to this stop [s].
     * @type {number}
     * @memberof WayReport
     */
    drivingTime: number;
    /**
     * The sum of break times between the departure from the previous stop and the arrival at this stop [s].
     * @type {number}
     * @memberof WayReport
     */
    breakTime: number;
}

/**
 * Check if a given object implements the WayReport interface.
 */
export function instanceOfWayReport(value: object): value is WayReport {
    if (!('distance' in value) || value['distance'] === undefined) return false;
    if (!('drivingTime' in value) || value['drivingTime'] === undefined) return false;
    if (!('breakTime' in value) || value['breakTime'] === undefined) return false;
    return true;
}

export function WayReportFromJSON(json: any): WayReport {
    return WayReportFromJSONTyped(json, false);
}

export function WayReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): WayReport {
    if (json == null) {
        return json;
    }
    return {
        
        'distance': json['distance'],
        'drivingTime': json['drivingTime'],
        'breakTime': json['breakTime'],
    };
}

  export function WayReportToJSON(json: any): WayReport {
      return WayReportToJSONTyped(json, false);
  }

  export function WayReportToJSONTyped(value?: WayReport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'distance': value['distance'],
        'drivingTime': value['drivingTime'],
        'breakTime': value['breakTime'],
    };
}

