/* tslint:disable */
/* eslint-disable */
/**
 * Sequence Optimization
 * With the Sequence Optimization service you can find the best route for your transports.
 *
 * The version of the OpenAPI document: 1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A way report contains a summary of the values of the events on the way from the previous stop to the current stop, including the driving time. The very first stop of a route has a way report with empty values.
 * @export
 * @interface WayReport
 */
export interface WayReport {
    /**
     * The driving distance from the previous stop to this stop [m].
     * @type {number}
     * @memberof WayReport
     */
    distance: number;
    /**
     * The driving time from the previous stop to this stop [s].
     * @type {number}
     * @memberof WayReport
     */
    drivingTime: number;
    /**
     * The sum of break times between the departure from the previous stop and the arrival at this stop [s].
     * @type {number}
     * @memberof WayReport
     */
    breakTime: number;
}

export function WayReportFromJSON(json: any): WayReport {
    return WayReportFromJSONTyped(json, false);
}

export function WayReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): WayReport {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'distance': json['distance'],
        'drivingTime': json['drivingTime'],
        'breakTime': json['breakTime'],
    };
}

export function WayReportToJSON(value?: WayReport | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'distance': value.distance,
        'drivingTime': value.drivingTime,
        'breakTime': value.breakTime,
    };
}

