/* tslint:disable */
/* eslint-disable */
/**
 * Sequence Optimization
 * With the Sequence Optimization service you can find the best route for your transports.
 *
 * The version of the OpenAPI document: 1.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Specifies break rule as well as maximum driving and travel time according to the chosen law.
 * 
 * If one of the concerned fields is specified as well the most restrictive rule holds. For example if a preset and maximumDrivingTime or maximumTravelTime are specified, the minimum of the specified value and the value defined by the preset counts.
 * 
 * See [here](./concepts/drivers-working-hours) for more information.
 * @export
 */
export const WorkingHoursPreset = {
    EU_DRIVING_TIME_REGULATION: 'EU_DRIVING_TIME_REGULATION',
    EU_DRIVING_TIME_REGULATION_FOR_LONG_DAY: 'EU_DRIVING_TIME_REGULATION_FOR_LONG_DAY',
    EU_WORKING_TIME_DIRECTIVE: 'EU_WORKING_TIME_DIRECTIVE',
    EU_WORKING_TIME_DIRECTIVE_FOR_LONG_DAY: 'EU_WORKING_TIME_DIRECTIVE_FOR_LONG_DAY',
    US_HOURS_OF_SERVICE_REGULATIONS: 'US_HOURS_OF_SERVICE_REGULATIONS'
} as const;
export type WorkingHoursPreset = typeof WorkingHoursPreset[keyof typeof WorkingHoursPreset];


export function instanceOfWorkingHoursPreset(value: any): boolean {
    for (const key in WorkingHoursPreset) {
        if (Object.prototype.hasOwnProperty.call(WorkingHoursPreset, key)) {
            if (WorkingHoursPreset[key as keyof typeof WorkingHoursPreset] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WorkingHoursPresetFromJSON(json: any): WorkingHoursPreset {
    return WorkingHoursPresetFromJSONTyped(json, false);
}

export function WorkingHoursPresetFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkingHoursPreset {
    return json as WorkingHoursPreset;
}

export function WorkingHoursPresetToJSON(value?: WorkingHoursPreset | null): any {
    return value as any;
}

export function WorkingHoursPresetToJSONTyped(value: any, ignoreDiscriminator: boolean): WorkingHoursPreset {
    return value as WorkingHoursPreset;
}

